[features]
seeds = false
[programs.localnet]
options_trading = "6xUQFHLbbfhayBwLBNSMfZfCmHNJJujWsS88qCtGfWdn"
cpi_examples = "6xUQFHLbbfhayBwLBNSMfZfCmHNJJujWsS88qCtGfWdn"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha tests/**/*.ts"
